simplify ci build and use caches

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -24,8 +24,8 @@ jobs:
       - name: Upload Maven Repository
         uses: actions/upload-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
           retention-days: 1
 
   examples-java-maven:
@@ -38,11 +38,12 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+          cache: 'maven'
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Create Maven 3 wrapper
         working-directory: examples/java
         run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
@@ -67,11 +68,12 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+          cache: 'maven'
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Create Maven 4 wrapper
         working-directory: examples/java
         run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=4.0.0-rc-5
@@ -96,11 +98,12 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+          cache: 'gradle'
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Run Java-Example with Gradle
         working-directory: examples/java
         run: gradle build
@@ -117,6 +120,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      - uses: coursier/cache-action@v7
       - name: Set up JDK 17
         uses: actions/setup-java@v5
         with:
@@ -125,14 +129,14 @@ jobs:
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
-      - name: Clear m2 cache except lazyval (because otherwise coursier will fail to resolve artifacts where only poms are downloaded)
-        run: |
-          mv ~/.m2/repository/de/qualityminds/lazyval /tmp/lazyval-backup || true
-          rm -rf ~/.m2/repository/*
-          mkdir -p ~/.m2/repository/de/qualityminds
-          mv /tmp/lazyval-backup ~/.m2/repository/de/qualityminds/lazyval || true
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
+#      - name: Clear m2 cache except lazyval (because otherwise coursier will fail to resolve artifacts where only poms are downloaded)
+#        run: |
+#          mv ~/.m2/repository/de/qualityminds/lazyval /tmp/lazyval-backup || true
+#          rm -rf ~/.m2/repository/*
+#          mkdir -p ~/.m2/repository/de/qualityminds
+#          mv /tmp/lazyval-backup ~/.m2/repository/de/qualityminds/lazyval || true
       - name: Download Mill Script
         working-directory: examples/java
         run: curl -L -s https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/${MILL_VERSION}/mill-dist-${MILL_VERSION}-mill.sh -o mill && chmod +x mill
@@ -159,11 +163,12 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+          cache: 'maven'
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Create Maven 3 wrapper
         working-directory: examples/kotlin
         run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
@@ -189,11 +194,12 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+          cache: 'maven'
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Create Maven 4 wrapper
         working-directory: examples/kotlin
         run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=4.0.0-rc-5
@@ -218,11 +224,12 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+          cache: 'gradle'
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Run Kotlin-Example with Gradle
         working-directory: examples/kotlin
         run: gradle build
@@ -248,14 +255,14 @@ jobs:
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
-      - name: Clear m2 cache except lazyval (because otherwise coursier will fail to resolve artifacts where only poms are downloaded)
-        run: |
-          mv ~/.m2/repository/de/qualityminds/lazyval /tmp/lazyval-backup || true
-          rm -rf ~/.m2/repository/*
-          mkdir -p ~/.m2/repository/de/qualityminds
-          mv /tmp/lazyval-backup ~/.m2/repository/de/qualityminds/lazyval || true
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
+#      - name: Clear m2 cache except lazyval (because otherwise coursier will fail to resolve artifacts where only poms are downloaded)
+#        run: |
+#          mv ~/.m2/repository/de/qualityminds/lazyval /tmp/lazyval-backup || true
+#          rm -rf ~/.m2/repository/*
+#          mkdir -p ~/.m2/repository/de/qualityminds
+#          mv /tmp/lazyval-backup ~/.m2/repository/de/qualityminds/lazyval || true
       - name: Download Mill Script
         working-directory: examples/kotlin
         run: curl -L -s https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/${MILL_VERSION}/mill-dist-${MILL_VERSION}-mill.sh -o mill && chmod +x mill
@@ -285,8 +292,8 @@ jobs:
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Create Maven 3 wrapper
         working-directory: examples/java-spi-dev
         run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
@@ -308,8 +315,8 @@ jobs:
       - name: Download Maven Repository
         uses: actions/download-artifact@v4
         with:
-          name: maven-repo
-          path: ~/.m2/repository/
+          name: maven-repo-lazyval
+          path: ~/.m2/repository/de/qualityminds/lazyval
       - name: Create Maven 3 wrapper
         working-directory: examples/kotlin-spi-dev
         run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
